modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="fundationbufull"
    version="1.0.0"
    displayName="Fundationbufull"
    description="Player Immortal Charm with full L2Hostility immunity"
    authors="example"

[[dependencies.fundationbufull]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fundationbufull]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"